# Generated by Django 5.0.7 on 2024-07-30 10:04

from django.db import migrations


def add_default_data(apps, schema_editor):
    Gym = apps.get_model("gym_app", "Gym")
    HallType = apps.get_model("gym_app", "HallType")
    Machine = apps.get_model("gym_app", "Machine")
    Employee = apps.get_model("gym_app", "Employee")
    Admin = apps.get_model("gym_app", "Admin")
    Hall = apps.get_model("gym_app", "Hall")
    Member = apps.get_model("gym_app", "Member")
    HallMachine = apps.get_model("gym_app", "HallMachine")

    # Adding default data to Gym
    Gym.objects.bulk_create(
        [
            Gym(
                name="Main Gym",
                type="Fitness",
                address_city="City A",
                address_street="Street 1",
            ),
            Gym(
                name="Wellness Center",
                type="Wellness",
                address_city="City B",
                address_street="Street 2",
            ),
            Gym(
                name="Health Club",
                type="Health",
                address_city="City C",
                address_street="Street 3",
            ),
        ]
    )

    # Adding default data to HallType
    HallType.objects.bulk_create(
        [
            HallType(name="SAUNA", code="SAUNA", type_description="Sauna Room"),
            HallType(
                name="TRAINING", code="TRAINING", type_description="Training Hall"
            ),
            HallType(name="YOGA", code="YOGA", type_description="Yoga Room"),
        ]
    )

    # Adding default data to Machine
    Machine.objects.bulk_create(
        [
            Machine(
                serial_number="M123",
                type="walking",
                model="Model A",
                brand="Brand X",
                status="operational",
            ),
            Machine(
                serial_number="M124",
                type="running",
                model="Model B",
                brand="Brand Y",
                status="operational",
            ),
            Machine(
                serial_number="M125",
                type="cycling",
                model="Model C",
                brand="Brand Z",
                status="operational",
            ),
        ]
    )

    # Adding default data to Employee
    Employee.objects.bulk_create(
        [
            Employee(
                name="John Doe",
                address_city="City A",
                address_street="Street 1",
                email="john.doe@example.com",
                gym_id=Gym.objects.get(name="Main Gym"),
            ),
            Employee(
                name="Jane Smith",
                address_city="City B",
                address_street="Street 2",
                email="jane.smith@example.com",
                gym_id=Gym.objects.get(name="Wellness Center"),
            ),
            Employee(
                name="Alice Johnson",
                address_city="City C",
                address_street="Street 3",
                email="alice.johnson@example.com",
                gym_id=Gym.objects.get(name="Health Club"),
            ),
        ]
    )

    # Adding default data to Admin
    Admin.objects.bulk_create(
        [
            Admin(
                name="Admin One",
                phone_number="1234567890",
                email="admin1@example.com",
                address_city="City A",
                address_street="Street 1",
                gym_id=Gym.objects.get(name="Main Gym"),
            ),
            Admin(
                name="Admin Two",
                phone_number="0987654321",
                email="admin2@example.com",
                address_city="City B",
                address_street="Street 2",
                gym_id=Gym.objects.get(name="Wellness Center"),
            ),
            Admin(
                name="Admin Three",
                phone_number="5555555555",
                email="admin3@example.com",
                address_city="City C",
                address_street="Street 3",
                gym_id=Gym.objects.get(name="Health Club"),
            ),
        ]
    )

    # Adding default data to Hall
    Hall.objects.bulk_create(
        [
            Hall(
                name="Hall A",
                users_capacity=30,
                gym_id=Gym.objects.get(name="Main Gym"),
                hall_type_id=HallType.objects.get(code="TRAINING"),
            ),
            Hall(
                name="Hall B",
                users_capacity=20,
                gym_id=Gym.objects.get(name="Wellness Center"),
                hall_type_id=HallType.objects.get(code="YOGA"),
            ),
            Hall(
                name="Hall C",
                users_capacity=25,
                gym_id=Gym.objects.get(name="Health Club"),
                hall_type_id=HallType.objects.get(code="SAUNA"),
            ),
        ]
    )

    # Adding default data to Member
    Member.objects.bulk_create(
        [
            Member(
                name="Member One",
                birth_date="2000-01-01",
                phone_number="1111111111",
                gym_id=Gym.objects.get(name="Main Gym"),
            ),
            Member(
                name="Member Two",
                birth_date="1990-06-15",
                phone_number="2222222222",
                gym_id=Gym.objects.get(name="Wellness Center"),
            ),
            Member(
                name="Member Three",
                birth_date="1985-12-30",
                phone_number="3333333333",
                gym_id=Gym.objects.get(name="Health Club"),
            ),
        ]
    )

    # Adding default data to HallMachine
    HallMachine.objects.bulk_create(
        [
            HallMachine(
                name="Hall A Machine 1",
                uid="HM001",
                hall_id=Hall.objects.get(name="Hall A"),
                machine_id=Machine.objects.get(serial_number="M123"),
            ),
            HallMachine(
                name="Hall B Machine 1",
                uid="HM002",
                hall_id=Hall.objects.get(name="Hall B"),
                machine_id=Machine.objects.get(serial_number="M124"),
            ),
            HallMachine(
                name="Hall C Machine 1",
                uid="HM003",
                hall_id=Hall.objects.get(name="Hall C"),
                machine_id=Machine.objects.get(serial_number="M125"),
            ),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "gym_app",
            "0001_initial",
        ),  # Adjust the dependency based on your initial migration file
    ]

    operations = [
        migrations.RunPython(add_default_data),
    ]
