# Generated by Django 5.0.7 on 2024-07-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hallmachine",
            name="uid",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
