# Generated by Django 5.0.7 on 2024-07-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_alter_hallmachine_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='users_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
