from gym_app.views.health_check_controller import HealthCheckViewSet
from gym_app.views.v1.admin_view import AdminViewSet
from gym_app.views.v1.employee_view import EmployeeViewSet
from gym_app.views.v1.gym_view import GymViewSet
from gym_app.views.v1.hall_view import HallViewSet
from gym_app.views.v1.member_view import MemberViewSet
from gym_app.views.v1.hall_type_view import HallTypeViewSet
from gym_app.views.v1.hall_machine_view import HallMachineViewSet
from gym_app.views.v1.machine_view import MachineViewSet
